name: GitHub App Dynamic Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      # - name: Generate GitHub App token
      #   id: app-token
      #   uses: actions/create-github-app-token@v2
      #   with:
      #     app-id: ${{ secrets.GH_APP_ID }}
      #     private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      # - name: Show token generated
      #   env:
      #     GH_TOKEN: ${{ steps.app-token.outputs.token }}
      #   run: |
      #     echo "GitHub App token generated"

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Git log
        run: git log --oneline

      - name: Clone myapp
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/sai411/myapp.git
